# /etc/ax25/ax25d.conf
#
# ax25d Configuration File.
#
# AX.25 Ports begin with a '['.
#
# Please note that the programs node and finger are not part of ax25-tools.
#
####################### Winlink
[N0CALL-10 VIA radio]
NOCALL   * * * * * *  L
default  * * * * * *  - pi /usr/local/bin/rmsgw rmsgw -l debug -P %d %U

